# Generated by Django 4.2.27 on 2026-02-01 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='todolist',
        ),
    ]
