# Generated by Django 4.2.27 on 2026-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_list_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(max_length=200),
        ),
    ]
