# Generated by Django 4.2.27 on 2026-02-12 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todolist_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='listid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='content',
            field=models.TextField(),
        ),
    ]
